from django.contrib import admin
from django.urls import path
from stocks.views import (
    login_page,
    home,
    search_companies,
    company_details,
    company_news,
    company_financials,
    company_announcements,
    company_market,
    company_shareholding,
    company_corporate_actions,
    test_ollama,
    company_ai_summary,
    company_openai_summary,
    company_yfinance,
    company_chat,
    logout_view,
    help_page,
    default_companies,
    tradingview_data,
    stocksbot_chat,
    stocksbot_page,
    price_data_api,
    live_price,         
    signup_page
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', login_page, name='login'),
    path('home/', home, name='home'),
    path('logout/', logout_view, name='logout'),
    path('help/', help_page, name='help'),
    path('search/', search_companies, name='search_companies'),
    path("company/<int:fincode>/", company_details, name="company_details"),
    path("company/<int:fincode>/news/", company_news, name="company_news"),
    path("company/<int:fincode>/financials/", company_financials, name="company_financials"),
    path("company/<int:fincode>/announcements/", company_announcements, name="company_announcements"),
    path("company-market/<int:fincode>/", company_market, name="company_market"),
    path("company-shareholding/<int:fincode>/", company_shareholding, name="company_shareholding"),
    path("company/<int:fincode>/corporate-actions/", company_corporate_actions, name="company_corporate_actions"),
    path("test-ollama/", test_ollama, name="test_ollama"),
    # path("company/<int:fincode>/ai-summary/", company_ai_summary, name="company_ai_summary"),  # COMMENTED – Ollama disabled
    path("company/<int:fincode>/openai-summary/", company_openai_summary),
    path("company/<int:fincode>/chat/", company_chat, name="company_chat"),
    path("company/<int:fincode>/yfinance/", company_yfinance, name="company_yfinance"),
    path('search/default/', default_companies, name='default_companies'),
    path('api/tradingview/<int:fincode>/', tradingview_data, name='tradingview_data'),
    path('stocksbot/chat/', stocksbot_chat, name='stocksbot_chat'),
    path('stocksbot/', stocksbot_page, name='stocksbot_page'),
    path('api/price/<str:symbol>/', price_data_api, name='price_data_api'),
    path('live-price/<str:symbol>/', live_price, name='live_price'),
     path('signup/', signup_page, name='signup'),
]