# Generated by Django 6.0.5 on 2026-06-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_announcementpdfcache_announcementchunk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementpdfcache',
            name='fincode',
        ),
        migrations.AddField(
            model_name='announcementpdfcache',
            name='scripcode',
            field=models.CharField(default='UNKNOWN', max_length=50),
            preserve_default=False,
        ),
    ]
