# Generated by Django 6.0.5 on 2026-06-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_remove_announcementpdfcache_fincode_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
        migrations.AlterModelOptions(
            name='announcementchunk',
            options={'ordering': ['pdf', 'chunk_index']},
        ),
        migrations.AddIndex(
            model_name='announcementchunk',
            index=models.Index(fields=['pdf', 'chunk_index'], name='stocks_anno_pdf_id_c54727_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementpdfcache',
            index=models.Index(fields=['scripcode'], name='stocks_anno_scripco_2a1840_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementpdfcache',
            index=models.Index(fields=['newsid'], name='stocks_anno_newsid_7f49b6_idx'),
        ),
    ]
