# Generated by Django 6.0.5 on 2026-06-19 06:22

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_delete_stock_alter_announcementchunk_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcementchunk',
            name='embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
