# Generated by Django 6.0.5 on 2026-06-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_announcementchunk_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=30)),
                ('interval', models.CharField(db_index=True, default='1m', max_length=5)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('open', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('close', models.FloatField()),
                ('volume', models.BigIntegerField(default=0)),
            ],
            options={
                'ordering': ['symbol', 'interval', 'timestamp'],
                'indexes': [models.Index(fields=['symbol', 'interval', 'timestamp'], name='stocks_pric_symbol_847410_idx')],
                'unique_together': {('symbol', 'interval', 'timestamp')},
            },
        ),
    ]
