# Generated by Django 6.0.5 on 2026-06-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_upstoxtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstrumentKeyMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50, unique=True)),
                ('upstox_key', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='upstoxtoken',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
