# Generated by Django 6.0.5 on 2026-06-24 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_instrumentkeymapping_alter_upstoxtoken_refresh_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livepricesnapshot',
            name='close_price',
        ),
        migrations.RemoveField(
            model_name='livepricesnapshot',
            name='high_price',
        ),
        migrations.RemoveField(
            model_name='livepricesnapshot',
            name='low_price',
        ),
        migrations.RemoveField(
            model_name='livepricesnapshot',
            name='open_price',
        ),
    ]
